version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - klik
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      JWT_SECRET: 2fe300b80c8f633d7adf115a1661905ecadbefbe
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: klik
      DB_USERNAME: klik_user
      DB_PASSWORD: 123123
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: klik_user
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: klik
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - klik
    restart: unless-stopped

networks:
  klik:
    driver: bridge

volumes:
  db:
    driver: local